/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "secil.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(currentTemperature, currentTemperature, AUTO)


PB_BIND(heatingSetpoint, heatingSetpoint, AUTO)


PB_BIND(awayHeatingSetpoint, awayHeatingSetpoint, AUTO)


PB_BIND(coolingSetpoint, coolingSetpoint, AUTO)


PB_BIND(awayCoolingSetpoint, awayCoolingSetpoint, AUTO)


PB_BIND(hvacMode, hvacMode, AUTO)


PB_BIND(relativeHumidity, relativeHumidity, AUTO)


PB_BIND(accessoryState, accessoryState, AUTO)


PB_BIND(supportPackageData, supportPackageData, 2)


PB_BIND(demandResponse, demandResponse, AUTO)


PB_BIND(awayMode, awayMode, AUTO)


PB_BIND(autoWake, autoWake, AUTO)


PB_BIND(localUiState, localUiState, AUTO)


PB_BIND(dateAndTime, dateAndTime, AUTO)


PB_BIND(SecilMessage, SecilMessage, 2)



