/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SECIL_PB_H_INCLUDED
#define PB_SECIL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _currentTemperature {
    int8_t currentTemperature;
} currentTemperature;

typedef struct _heatingSetpoint {
    int8_t heatingSetpoint;
} heatingSetpoint;

typedef struct _awayHeatingSetpoint {
    int8_t awayHeatingSetpoint;
} awayHeatingSetpoint;

typedef struct _coolingSetpoint {
    int8_t coolingSetpoint;
} coolingSetpoint;

typedef struct _awayCoolingSetpoint {
    int8_t awayCoolingSetpoint;
} awayCoolingSetpoint;

typedef struct _hvacMode {
    int8_t hvacMode;
} hvacMode;

typedef struct _relativeHumidity {
    bool relativeHumidity;
} relativeHumidity;

typedef struct _accessoryState {
    bool accessoryState;
} accessoryState;

typedef struct _supportPackageData {
    char supportPackageData[256];
} supportPackageData;

typedef struct _demandResponse {
    bool demandResponse;
} demandResponse;

typedef struct _awayMode {
    bool awayMode;
} awayMode;

typedef struct _autoWake {
    bool autoWake;
} autoWake;

typedef struct _localUiState {
    int8_t localUiState;
} localUiState;

typedef struct _SecilMessage {
    int32_t id;
    pb_size_t which_payload;
    union _SecilMessage_payload {
        currentTemperature currentTemperature;
        heatingSetpoint heatingSetpoint;
        awayHeatingSetpoint awayHeatingSetpoint;
        coolingSetpoint coolingSetpoint;
        awayCoolingSetpoint awayCoolingSetpoint;
        hvacMode hvacMode;
        relativeHumidity relativeHumidity;
        accessoryState accessoryState;
        supportPackageData supportPackageData;
        demandResponse demandResponse;
        awayMode awayMode;
        autoWake autoWake;
        localUiState localUiState;
    } payload;
} SecilMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define currentTemperature_init_default          {0}
#define heatingSetpoint_init_default             {0}
#define awayHeatingSetpoint_init_default         {0}
#define coolingSetpoint_init_default             {0}
#define awayCoolingSetpoint_init_default         {0}
#define hvacMode_init_default                    {0}
#define relativeHumidity_init_default            {0}
#define accessoryState_init_default              {0}
#define supportPackageData_init_default          {""}
#define demandResponse_init_default              {0}
#define awayMode_init_default                    {0}
#define autoWake_init_default                    {0}
#define localUiState_init_default                {0}
#define SecilMessage_init_default                {0, 0, {currentTemperature_init_default}}
#define currentTemperature_init_zero             {0}
#define heatingSetpoint_init_zero                {0}
#define awayHeatingSetpoint_init_zero            {0}
#define coolingSetpoint_init_zero                {0}
#define awayCoolingSetpoint_init_zero            {0}
#define hvacMode_init_zero                       {0}
#define relativeHumidity_init_zero               {0}
#define accessoryState_init_zero                 {0}
#define supportPackageData_init_zero             {""}
#define demandResponse_init_zero                 {0}
#define awayMode_init_zero                       {0}
#define autoWake_init_zero                       {0}
#define localUiState_init_zero                   {0}
#define SecilMessage_init_zero                   {0, 0, {currentTemperature_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define currentTemperature_currentTemperature_tag 1
#define heatingSetpoint_heatingSetpoint_tag      1
#define awayHeatingSetpoint_awayHeatingSetpoint_tag 1
#define coolingSetpoint_coolingSetpoint_tag      1
#define awayCoolingSetpoint_awayCoolingSetpoint_tag 1
#define hvacMode_hvacMode_tag                    1
#define relativeHumidity_relativeHumidity_tag    1
#define accessoryState_accessoryState_tag        1
#define supportPackageData_supportPackageData_tag 1
#define demandResponse_demandResponse_tag        1
#define awayMode_awayMode_tag                    1
#define autoWake_autoWake_tag                    1
#define localUiState_localUiState_tag            1
#define SecilMessage_id_tag                      1
#define SecilMessage_currentTemperature_tag      2
#define SecilMessage_heatingSetpoint_tag         3
#define SecilMessage_awayHeatingSetpoint_tag     4
#define SecilMessage_coolingSetpoint_tag         5
#define SecilMessage_awayCoolingSetpoint_tag     6
#define SecilMessage_hvacMode_tag                7
#define SecilMessage_relativeHumidity_tag        8
#define SecilMessage_accessoryState_tag          9
#define SecilMessage_supportPackageData_tag      10
#define SecilMessage_demandResponse_tag          11
#define SecilMessage_awayMode_tag                12
#define SecilMessage_autoWake_tag                13
#define SecilMessage_localUiState_tag            14

/* Struct field encoding specification for nanopb */
#define currentTemperature_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    currentTemperature,   1)
#define currentTemperature_CALLBACK NULL
#define currentTemperature_DEFAULT NULL

#define heatingSetpoint_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    heatingSetpoint,   1)
#define heatingSetpoint_CALLBACK NULL
#define heatingSetpoint_DEFAULT NULL

#define awayHeatingSetpoint_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    awayHeatingSetpoint,   1)
#define awayHeatingSetpoint_CALLBACK NULL
#define awayHeatingSetpoint_DEFAULT NULL

#define coolingSetpoint_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    coolingSetpoint,   1)
#define coolingSetpoint_CALLBACK NULL
#define coolingSetpoint_DEFAULT NULL

#define awayCoolingSetpoint_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    awayCoolingSetpoint,   1)
#define awayCoolingSetpoint_CALLBACK NULL
#define awayCoolingSetpoint_DEFAULT NULL

#define hvacMode_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    hvacMode,          1)
#define hvacMode_CALLBACK NULL
#define hvacMode_DEFAULT NULL

#define relativeHumidity_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     relativeHumidity,   1)
#define relativeHumidity_CALLBACK NULL
#define relativeHumidity_DEFAULT NULL

#define accessoryState_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     accessoryState,    1)
#define accessoryState_CALLBACK NULL
#define accessoryState_DEFAULT NULL

#define supportPackageData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   supportPackageData,   1)
#define supportPackageData_CALLBACK NULL
#define supportPackageData_DEFAULT NULL

#define demandResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     demandResponse,    1)
#define demandResponse_CALLBACK NULL
#define demandResponse_DEFAULT NULL

#define awayMode_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     awayMode,          1)
#define awayMode_CALLBACK NULL
#define awayMode_DEFAULT NULL

#define autoWake_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     autoWake,          1)
#define autoWake_CALLBACK NULL
#define autoWake_DEFAULT NULL

#define localUiState_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    localUiState,      1)
#define localUiState_CALLBACK NULL
#define localUiState_DEFAULT NULL

#define SecilMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,currentTemperature,payload.currentTemperature),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heatingSetpoint,payload.heatingSetpoint),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,awayHeatingSetpoint,payload.awayHeatingSetpoint),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,coolingSetpoint,payload.coolingSetpoint),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,awayCoolingSetpoint,payload.awayCoolingSetpoint),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hvacMode,payload.hvacMode),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,relativeHumidity,payload.relativeHumidity),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,accessoryState,payload.accessoryState),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,supportPackageData,payload.supportPackageData),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,demandResponse,payload.demandResponse),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,awayMode,payload.awayMode),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,autoWake,payload.autoWake),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,localUiState,payload.localUiState),  14)
#define SecilMessage_CALLBACK NULL
#define SecilMessage_DEFAULT NULL
#define SecilMessage_payload_currentTemperature_MSGTYPE currentTemperature
#define SecilMessage_payload_heatingSetpoint_MSGTYPE heatingSetpoint
#define SecilMessage_payload_awayHeatingSetpoint_MSGTYPE awayHeatingSetpoint
#define SecilMessage_payload_coolingSetpoint_MSGTYPE coolingSetpoint
#define SecilMessage_payload_awayCoolingSetpoint_MSGTYPE awayCoolingSetpoint
#define SecilMessage_payload_hvacMode_MSGTYPE hvacMode
#define SecilMessage_payload_relativeHumidity_MSGTYPE relativeHumidity
#define SecilMessage_payload_accessoryState_MSGTYPE accessoryState
#define SecilMessage_payload_supportPackageData_MSGTYPE supportPackageData
#define SecilMessage_payload_demandResponse_MSGTYPE demandResponse
#define SecilMessage_payload_awayMode_MSGTYPE awayMode
#define SecilMessage_payload_autoWake_MSGTYPE autoWake
#define SecilMessage_payload_localUiState_MSGTYPE localUiState

extern const pb_msgdesc_t currentTemperature_msg;
extern const pb_msgdesc_t heatingSetpoint_msg;
extern const pb_msgdesc_t awayHeatingSetpoint_msg;
extern const pb_msgdesc_t coolingSetpoint_msg;
extern const pb_msgdesc_t awayCoolingSetpoint_msg;
extern const pb_msgdesc_t hvacMode_msg;
extern const pb_msgdesc_t relativeHumidity_msg;
extern const pb_msgdesc_t accessoryState_msg;
extern const pb_msgdesc_t supportPackageData_msg;
extern const pb_msgdesc_t demandResponse_msg;
extern const pb_msgdesc_t awayMode_msg;
extern const pb_msgdesc_t autoWake_msg;
extern const pb_msgdesc_t localUiState_msg;
extern const pb_msgdesc_t SecilMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define currentTemperature_fields &currentTemperature_msg
#define heatingSetpoint_fields &heatingSetpoint_msg
#define awayHeatingSetpoint_fields &awayHeatingSetpoint_msg
#define coolingSetpoint_fields &coolingSetpoint_msg
#define awayCoolingSetpoint_fields &awayCoolingSetpoint_msg
#define hvacMode_fields &hvacMode_msg
#define relativeHumidity_fields &relativeHumidity_msg
#define accessoryState_fields &accessoryState_msg
#define supportPackageData_fields &supportPackageData_msg
#define demandResponse_fields &demandResponse_msg
#define awayMode_fields &awayMode_msg
#define autoWake_fields &autoWake_msg
#define localUiState_fields &localUiState_msg
#define SecilMessage_fields &SecilMessage_msg

/* Maximum encoded size of messages (where known) */
#define SECIL_PB_H_MAX_SIZE                      SecilMessage_size
#define SecilMessage_size                        272
#define accessoryState_size                      2
#define autoWake_size                            2
#define awayCoolingSetpoint_size                 11
#define awayHeatingSetpoint_size                 11
#define awayMode_size                            2
#define coolingSetpoint_size                     11
#define currentTemperature_size                  11
#define demandResponse_size                      2
#define heatingSetpoint_size                     11
#define hvacMode_size                            11
#define localUiState_size                        11
#define relativeHumidity_size                    2
#define supportPackageData_size                  258

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
